# Generated by Django 5.1.5 on 2025-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
