# Generated by Django 5.1.5 on 2025-03-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(max_digits=7, decimal_places=2, default=0.00)),  # Correctly defined with default
                ('quantity', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
